project/lovisto/urls.py
from django.shortcuts import redirect

from . import views
from django.urls import path
from django.conf.urls import url

urlpatterns = [
    path('', views.index, name="index"),
    path('aportaciones', views.aportaciones),
    path('user', views.user_page),
    path('aemet/<str:municipio>-id<int:municipio_id>', views.aportacion_aemet_page),
    path('wiki/<str:articulo>', views.aportacion_wiki_page),
    path('youtube/<str:video>', views.aportacion_youtube_page),
    path('reddit/<str:id_reddit>', views.aportacion_reddit_page),
    path('no_reconocido/<str:titulo>', views.aportacion_no_reconocido),
    path('modo_oscuro', views.modo_oscuro),
    path('modo_normal', views.modo_normal),
    path('comentarios', views.tipo_comentarios),
    path('informacion', views.informacion),
    url(r'^like/$', views.like_content, name="like_content"),
    url(r'^dislike/$', views.dislike_content, name="dislike_content"),
    url(r'^like_aportacion/$', views.like_aportacion, name="like_aportacion"),
    url(r'^dislike_aportacion/$', views.dislike_aportacion, name="dislike_aportacion")
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('lovisto.urls')),
    path('admin/', admin.site.urls),
]

project/lovisto/models.py
from django.contrib.auth.models import User
from django.db import models


class Contenido(models.Model):
    url = models.CharField(max_length=256)
    titulo = models.CharField(max_length=256)
    url_path = models.CharField(max_length=256, default='')
    descripcion = models.TextField(blank=True)
    html = models.TextField(blank=True)
    html_resumido = models.TextField(blank=True)
    tipo = models.CharField(max_length=256)
    user = models.CharField(max_length=256, default=User)
    fecha = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    is_liked = models.BooleanField
    is_disLiked = models.BooleanField
    dislikes = models.ManyToManyField(User, related_name='dislikes', blank=True)

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

    num_likes = total_likes
    num_dislikes = total_dislikes

    def __str__(self):
        return str(self.titulo) + "--> id =" + str(self.id)


class Comentario(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=128)
    cuerpo = models.TextField(blank=True)
    fecha = models.DateTimeField(auto_now=True)
    user_id = models.IntegerField(blank=False, default=0)
    user_name = models.CharField(max_length=128, default='')
    image_url = models.CharField(max_length=256, blank=True, null=True)

    def __str__(self):
        return str(self.titulo) + "--> id =" + str(self.id) + "--> contenido =" + str(self.contenido.titulo)


class Modo(models.Model):
    user = models.CharField(max_length=256, default=User)
    modo_oscuro = models.BooleanField()

project/lovisto/forms.py
from django import forms
from .models import Comentario


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['titulo', 'cuerpo', 'image_url']

project/lovisto/views.py
import urllib

from django.contrib.auth.forms import AuthenticationForm
from lxml import html, etree

from .models import Contenido, Comentario, Modo
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import redirect, render
from django.template import loader
#INDICAR QUE SE HA USADO LA LIBRERIA XML TO DICT
import xmltodict
import json
from bs4 import BeautifulSoup
from .forms import ComentarioForm


form_logout = """
Hey! You are authenticated as '{{user}}'.
<form action="" method="POST">
    <br/input type="submit" value="Logout">
</form>
"""

no_usuario = False
menu_links = []


def links(request, string):
    global menu_links
    menu_links = []
    if string == "index":
        link = "<a href='" + "/aportaciones" + "'>" + "Todo" + "</a>"
        menu_links.append(link)
        if request.user.is_authenticated:
            link = "<a href='" + "/user" + "'>" + "User" + "</a>"
            menu_links.append(link)
    elif string == "user":
        link = "<a href='" + "/" + "'>" + "Inicio" + "</a>"
        menu_links.append(link)
        link = "<a href='" + "/aportaciones" + "'>" + "Todo" + "</a>"
        menu_links.append(link)
    elif string == "aportacion":
        link = "<a href='" + "/" + "'>" + "Inicio" + "</a>"
        menu_links.append(link)
        link = "<a href='" + "/aportaciones" + "'>" + "Todo" + "</a>"
        menu_links.append(link)
        if request.user.is_authenticated:
            link = "<a href='" + "/user" + "'>" + "User" + "</a>"
            menu_links.append(link)
    elif string == 'aportaciones':
        link = "<a href='" + "/" + "'>" + "Inicio" + "</a>"
        menu_links.append(link)
        if request.user.is_authenticated:
            link = "<a href='" + "/user" + "'>" + "User" + "</a>"
            menu_links.append(link)

    link = "<a href='" + "/aportaciones?format=xml" + "'>" + "Descargar aportaciones como fichero XML" + "</a>"
    menu_links.append(link)
    link = "<a href='" + "/aportaciones?format=json" + "'>" + "Descargar aportaciones como fichero JSON" + "</a>"
    menu_links.append(link)
    link = "<a href='" + "/comentarios?format=xml" + "'>" + "Descargar comentarios como fichero XML" + "</a>"
    menu_links.append(link)
    link = "<a href='" + "/comentarios?format=json" + "'>" + "Descargar comentarios como fichero JSON" + "</a>"
    menu_links.append(link)
    link = "<a href='" + "/informacion" + "'>" + "Información de la aplicación" + "</a>"
    menu_links.append(link)

    try:
        modo = Modo.objects.get(user=request.user)
        oscuro = modo.modo_oscuro
    except Modo.DoesNotExist:
        oscuro = False

    if request.user.is_authenticated:
        if oscuro:
            link = "<a class ='active' href='" + "/modo_normal" + "'>" + "Modo Normal" + "</a>"
            menu_links.append(link)
        else:
            link = "<a class ='active' href='" + "/modo_oscuro" + "'>" + "Modo Oscuro" + "</a>"
            menu_links.append(link)


def parse_recurso(request, recurso):
    url = request.POST['url']
    titulo = request.POST['titulo']
    descripcion = request.POST['descripcion']
    if "/es/eltiempo/prediccion/municipios/" in recurso:
        recurso = recurso.split('/')[5]
        municipio, id_municipio = recurso.split('-id')
        url_path = "/aemet/" + municipio + "-id" + id_municipio
        xml_url = "https://www.aemet.es/xml/municipios/localidad_" + id_municipio + ".xml"
        xml = urllib.request.urlopen(xml_url)
        xmldict = xmltodict.parse(xml.read())
        provincia = xmldict["root"]["provincia"]
        prediccion = []
        for dia in xmldict["root"]["prediccion"]["dia"]:
            fecha = dia["@fecha"]
            temperatura = dia["temperatura"]["maxima"] + "/" + dia["temperatura"]["minima"]
            sensacion = dia["sens_termica"]["maxima"] + "/" + dia["sens_termica"]["minima"]
            humedad = dia["humedad_relativa"]["maxima"] + "/" + dia["humedad_relativa"]["minima"]
            dia = (fecha + ". Temperatura: " + temperatura + ", sensación: "
                   + sensacion + ", humedad: " + humedad)
            prediccion.append(dia)
            prediccion_html = ""
            for p in prediccion:
                d = "<li>" + p + "</li>"
                prediccion_html = prediccion_html + d
        print(url)
        html = ("<div class='aemet'>" +
                "<p>Datos AEMET para " + municipio.title() + " (" + provincia + ")</p>" +
                prediccion_html +
                "<p>Copyright AEMET. <a href='" + url + "'> Página original en AEMET </a></p>" +
                "</div>"
                )
    elif "/wiki/" in recurso:
        articulo = recurso.split('/')[2]
        url_path = "/wiki/" + articulo
        xml_url = "https://es.wikipedia.org/w/api.php?action=query&format=xml&titles="+articulo+"&prop=extracts&exintro&explaintext"
        json_url = "https://es.wikipedia.org/w/api.php?action=query&titles="+articulo+"&prop=pageimages&format=json&pithumbsize=100"
        xml = urllib.request.urlopen(xml_url)
        xmldict = xmltodict.parse(xml.read())
        json_file = urllib.request.urlopen(json_url)
        json_dict = json.loads(json_file.read().decode('utf8'))
        texto_articulo = xmldict["api"]["query"]["pages"]["page"]["extract"]['#text']
        id_json = str(xmldict["api"]["query"]["pages"]["page"]["@pageid"])
        if len(texto_articulo) > 400:
            texto_articulo = texto_articulo[0:400]
        imagen = json_dict["query"]["pages"][id_json]["thumbnail"]["source"]
        html = (
                "<div class="'wikipedia'">" +
                "<p>Artíıculo Wikipedia: "+articulo+"</p>" +
                "<img src='"+imagen+"' width='150' height='150'>" +
                "<p>"+texto_articulo+"</p>" +
                "<p>Copyright Wikipedia. " +
                "<a href='https://es.wikipedia.org/wiki/"+articulo+"'>Artículo original</a></p>"+
                "</div>"
        )
    elif "/watch?v=" in recurso:
        video = recurso.split('watch?v=')[1]
        url_path = "/youtube/" + video
        json_url = "https://www.youtube.com/oembed?format=json&url=https://www.youtube.com/watch?v="+video
        json_file = urllib.request.urlopen(json_url)
        json_dict = json.loads(json_file.read().decode('utf8'))
        title = json_dict["title"]
        autor = json_dict["author_name"]
        video_embed = json_dict["html"]
        html = (
                "<div class='youtube'>" +
                "<p>Video YouTube: " + title + "</p>" +
                video_embed +
                "<p>Autor: " + autor + ". " +
                "<a href='"+url+"'>Video en YouTube</a></p>" +
                "</div>"
        )
    elif ("/r/" in recurso) and ("/comments/" in recurso):
        recurso = recurso.split("/")
        subreddit = recurso[2]
        id_reddit = recurso[4]
        title = recurso[5]
        url_path ="/reddit/"+id_reddit
        json_url = ("https://www.reddit.com/r/"+subreddit+"/comments/"+id_reddit+"/.json")
        json_file = urllib.request.urlopen(json_url)
        json_dict = json.loads(json_file.read().decode('utf8'))
        subreddit = json_dict[0]["data"]["children"][0]["data"]["subreddit"]
        title_reddit = json_dict[0]["data"]["children"][0]["data"]["title"]
        text_reddit = json_dict[0]["data"]["children"][0]["data"]["selftext"]
        aprobacion = json_dict[0]["data"]["children"][0]["data"]["upvote_ratio"]
        url_reddit = json_dict[0]["data"]["children"][0]["data"]["url"]
        if "i.redd.it" in url_reddit:
            html=("<div class='reddit'>"+
                "<p>Nota Reddit: " + title_reddit + "</p>"+
                "<img src='"+url_reddit+"' width='150' height='150'>"+
                "<p><a href='"+url+"'>Publicado "+
                "en "+ subreddit+"</a>, Aprobacion: "+str(aprobacion)+".</p>"
                "</div>")
        else:
            html=("<div class='reddit'>"+
                "<p>Nota Reddit: " + title_reddit + "</p>"+
                "<p>"+text_reddit+"</p>"+
                "<p><a href='"+url_reddit+"'>Publicado "+
                "en "+ subreddit+"</a>, Aprobacion: "+str(aprobacion)+".</p>"
                "</div>")
    else:
        req = urllib.request.urlopen(url)
        soup = BeautifulSoup(req, 'html.parser')
        ogTitle = soup.find('meta', property='og:title')
        if ogTitle:
            title = ogTitle['content']
        ogImage = soup.find('meta', property='og:image')
        if ogImage:
            imagen = ogImage['content']

        if ogTitle and ogImage:
            html= ("<div class ='og'>" +
            "<p>" + title + "</p>" +
            "<img src = '" + imagen + "'>" +
            "</div>")
        elif ogTitle and not ogImage:
            html = ("<div class ='og'>" +
                    "<p>" + title + "</p>" +
                    "</div>")
        elif ogImage and not ogTitle:
            html = ("<div class ='og'>" +
                    "<p>" + titulo + "</p>" +
                    "<img src = '" + imagen + "'>" +
                    "</div>")
        else:
            html = ("<div class ='og'>" +
            "<p> Información extendida no disponible </p>"+
            "</div>")

        url_path = "/no_reconocido/" + titulo

    html_resumido = (
            "<a href='" + url_path + "'>" + titulo + "</a>"
    )
    content = Contenido(url=url, titulo=titulo, url_path=url_path, descripcion=descripcion,
                        html=html, html_resumido=html_resumido, tipo="no_reconocido", user=request.user)
    content.save()

    if request.user.is_authenticated:
        form_login = form_logout
        authenticated = True
    else:
        form_login = AuthenticationForm()
        authenticated = False

    user = request.user
    content_list = Contenido.objects.all()
    if len(content_list) > 10:
        content_list = list(content_list)

project/lovisto/templates/lovisto/aportacion.html
{% extends 'lovisto/schema.html' %}
{% block body %}
{% load static %}
<head>
    {% if modo_oscuro %}
        <link rel="stylesheet" href="{% static 'css_oscuro/index_oscuro.css' %}">
    {% else %}
         <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endif %}
</head>
    <p></p>
    <div class="bg-3">
        <h2> INFORMACIÓN DE LA APORTACIÓN </h2>
    </div>
    <div class="info">
        <p>Título: {{ content.titulo }}</p>
        <p>Sitio web aportado: {{ content.url }}</p>
        <p>Descripción: {{ content.descripcion }}</p>
        <p>Aportación realizada por: {{ content.user }}</p>
        <p>Fecha de la aportación: {{ content.fecha }}</p>
        <p>------------------------Información extendida ------------------------</p>
        {{content.html | safe}}
    </div>
    <p></p>
    <div class="bg-3">
        <h2> COMENTARIOS  </h2>
    </div>
    <div class="info">
        <div class="row">
        {% for comentario in content.comentario_set.all %}
            <div class="col-lg-6 col-md-8 col-sm-12 ">
                <p><h4> Comentario: </h4></p>
                <li>Title: {{ comentario.titulo }}</li>
                <li>Body: {{ comentario.cuerpo }}</li>
                <li>Date: {{ comentario.fecha }}</li>
                <li>User: {{ comentario.user_name }}</li>
                <li>User Id: {{ comentario.user_id }}</li>
                {% if comentario.image_url %}
                    <img src="{{comentario.image_url}}" width="150" height="150">
                {% endif %}
                {% for image in comentario.comentarioimage_set.all %}
                    <img src="{{image}}" width="150" height="150">
                {% endfor %}

            </div>
        {% endfor %}
        </div>
    </div>
    {% if request.user.is_authenticated %}
        <p></p>
        <div class="bg-2">
        <h4>Añade un comentario</h4>
        <form action="" method= "POST">
            {% csrf_token %}
            Titulo: <input type="text" name="titulo">
            Cuerpo: <input type="text" name="cuerpo">
            URL de imagen: <input type="text" name="url_imagen">
            <button type="submit" name="action" value="Añadir comentario">
                    <img src ="{% static 'submit.png' %}" width="170" height="70"></button>
        </form>

        </div>
        <p></p>
        <div class="bg-3">
            <h2> VOTOS </h2>
        </div>
        <div class="bg-2">
            <h4>Vota esta aportación</h4>
            {% if content.is_liked %}
                <p>Ya votaste 'like', pulsa 'dislike' para cambiar tu voto</p>
                 <form action="{%url 'dislike_aportacion' %}" method="POST">
                     {% csrf_token %}
                    <button type="submit" name="content_id" value="{{ content.id }}"
                            class = "btn-dislike"><img src ="{% static 'dislike.png' %}" width="70" height="30"></button>
                 </form>
            {% elif content.is_disliked %}
                <p>Ya votaste 'dislike', pulsa 'like' para cambiar tu voto</p>
                <form action="{%url 'like_aportacion' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" name="content_id" value="{{ content.id }}"
                            class = "btn-dislike"><img src ="{% static 'like.jpg' %}" width="70" height="30"></button>
                </form>
            {% else %}
                <p>
                 <form action="{%url 'like_aportacion' %}" method="POST">
                    {% csrf_token %}
                   <button type="submit" name="content_id" value="{{ content.id }}"
                            class = "btn-dislike"><img src ="{% static 'like.jpg' %}" width="70" height="30"></button>
                 </form>
                 <form action="{%url 'dislike_aportacion' %}" method="POST">
                     {% csrf_token %}
                   <button type="submit" name="content_id" value="{{ content.id }}"
                            class = "btn-dislike"><img src ="{% static 'dislike.png' %}" width="70" height="30"></button>
                 </form>
                 </p>
            {% endif %}
            <p>Votos positivos: {{content.num_likes}} ----- Votos negativos:{{ content.num_dislikes }}</p>

        </div>
    {% endif %}
{% endblock %}

project/lovisto/templates/lovisto/aportaciones.html
{% extends 'lovisto/schema.html' %}
{% block body %}
{% load static %}
<head>
    {% if modo_oscuro %}
        <link rel="stylesheet" href="{% static 'css_oscuro/index_oscuro.css' %}">
    {% else %}
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endif %}
</head>
    <p></p>
    <div class="bg-3">
        <h2> APORTACIONES </h2>
    </div>
    <p></p>
    {% if content_list %}
        <div class="info">
            <div class="row">
                <div class="col-lg-12 col-md-10 col-sm-8">
                    {% for content in content_list %}
                        <li>{{ content.html_resumido | safe }}</li>
                        <p></p>
                    {% endfor %}
                    <p></p>
                </div>
            </div>
        </div>
    {% else %}
        <div class="info">
            <p></p>
            <h4>No hay contenido aún, sé el primero y aporta tu primer sitio</h4>
            <p></p>
        </div>
    {% endif %}
{% endblock %}

project/lovisto/templates/lovisto/index.html
{% extends 'lovisto/schema.html' %}
{% block body %}
{% load static %}
<head>
    {% if modo_oscuro %}
        <link rel="stylesheet" href="{% static 'css_oscuro/index_oscuro.css' %}">
    {% else %}
         <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endif %}
</head>
    {% if content_list %}
        <p></p>
        <div class="bg-3">
            <h2>APORTACIONES MÁS RECIENTES:</h2>
        </div>
        {% for content in content_list %}
            <p></p>
            <div class="info">
                <div class="col-lg-12 col-md-10 col-sm-8">
                    <p><h4> Aportación: </h4></p>
                        <p>Título: {{ content.titulo }}</p>
                        <p>Sitio web aportado: {{ content.url }}</p>
                        <p>Descripción: {{ content.descripcion }}</p>
                        <p><a href="{{content.url_path}}">Pagina de aportación</a></p>
                        <p>Aportación realizada por: {{ content.user }}</p>
                        <p>Fecha de la aportación: {{ content.fecha }}</p>
                        <p>------------------------Información extendida ------------------------</p>
                                {{content.html | safe}}
                </div>
            </div>
            {% if is_authenticated %}
                <p></p>
                <div class="bg-2">
                    <p>Vota esta aportación</p>
                    {% if content.is_liked %}
                        Ya votaste 'like', pulsa 'dislike' para cambiar tu voto
                         <form action="{%url 'dislike_content' %}" method="POST">
                             {% csrf_token %}
                             <button type="submit" name="content_id" value="{{ content.id }}"
                                     class = "btn-dislike"><img src ="{% static 'dislike.png' %}" width="70" height="30"></button>
                         </form>
                    {% elif content.is_disliked %}
                        Ya votaste 'dislike', pulsa 'like' para cambiar tu voto
                        <form action="{%url 'like_content' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" name="content_id" value="{{ content.id }}"
                                    class = "btn-like"><img src ="{% static 'like.jpg' %}" width="70" height="30"></button>
                         </form>
                    {% else %}
                         <form action="{%url 'like_content' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" name="content_id" value="{{ content.id }}"
                                    class = "btn-like"><img src ="{% static 'like.jpg' %}" width="70" height="30"></button>
                         </form>
                         <form action="{%url 'dislike_content' %}" method="POST">
                             {% csrf_token %}
                             <button type="submit" name="content_id" value="{{ content.id }}"
                                     class = "btn-dislike"><img src ="{% static 'dislike.png' %}" width="70" height="30"></button>
                         </form>
                    {% endif %}
                    <p>Votos positivos: {{content.num_likes}} ----- Votos negativos:{{ content.num_dislikes }}</p>
                </div>
            {% endif %}
        {% endfor %}
        {% if request.user.is_authenticated %}
            {% if content_user_list %}
                <p></p>
                 <div class="bg-3">
                     <h2>TUS ÚLTIMAS APORTACIONES SON:</h2>
                 </div>
                <div class="info">
                    {% for content in content_user_list %}
                        <p>Aportación realizada por: {{ content.user }} --> {{ content.html_resumido | safe }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <p></p>
        {% endif %}
    {% else %}
        <p></p>
        <div class="info">
            <p></p>
            <h4>No hay contenido aún, sé el primero y aporta tu primer sitio</h4>
            <p></p>
        </div>
        <p></p>
    {% endif %}

    {% if is_authenticated %}
        <div class="bg-2">
            <p>Añade aportacion</p>
            <form action="" method= "POST">
                {% csrf_token %}
                Url: <input type="text" name="url">
                Titulo: <input type="text" name="titulo">
                Descripción: <input type="text" name="descripcion">
                <button type="submit" name="action" value="Añadir aportación">
                    <img src ="{% static 'submit.png' %}" width="170" height="70"></button>
            </form>
        </div>
    {% endif %}
    {% endblock %}

project/lovisto/templates/lovisto/informacion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>informacion</title>
</head>
<body>
    <h2>Proyecto final Lo Visto. Asignatura: SAT</h2>
    <p>Este proyecto ha sido realizado por Emilio Castejón Toribio, alumno de Ingeniería de
        Tecnologías de Telecomunicacion en la URJC de Fuenlabrada.</p>

    <p>El proyecto se basa en crear una aplicación django que nos sirva algo parecido a una red social como
        instagram o facebook, donde los usuarios pueden visitar los contenidos que sube la gente, y subir ellos
        su propio contenido si están registrados. Estos contenidos como en cualquier red social, pueden ser
        votados y comentados por los usuarios que están registrados.</p>

    <p>La aplicación consiste en:</p>

    <p>Una página principal en la que podemos ver las ultimas aportaciones y
        votarlas -> <a href="/">Pagina principal</a></p>
    <p>Una página con todas las aportaciones -> <a href="/aportaciones">Todo</a></p>
    <p>Una página del perfil del usuario con los contenidos, votos y comentarios realizados por él
        (si está autenticado)-> <a href="/user">User</a></p>
    <p>Una página para cada aportación, en la que podemos ver los comentarios y los votos de esa
        aportación, y añadir nuevos si estamos registrados</p>
</body>
</html>

project/lovisto/templates/lovisto/schema.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/jpg" href="{% static 'favicon.jpg' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% if modo_oscuro %}
        <link rel="stylesheet" href="{% static 'css_oscuro/schema_oscuro.css' %}">
    {% else %}
         <link rel="stylesheet" href="{% static 'css/schema.css' %}">
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        {% if modo_oscuro %}
            <div class="col-lg-6 col-md-8 col-sm-12 "><img src="{% static 'URJC-Logo.png' %}" width="700" height="200"></div>
        {% else %}
            <div class="col-lg-6 col-md-8 col-sm-12 "><img src="{% static 'URJC-Logo-normal.png' %}" width="700" height="200"></div>
        {% endif %}
        <div class="col-lg-6 col-md-8  col-sm-12">
            <div class="login1">
                <div class="login2">
                    {% if request.user.is_authenticated %}
                        <div class="texto">
                            <p>Hey! You are login as '{{request.user}}'</p>
                            <form action="{%url 'index' %}" method= "POST">
                                   {% csrf_token %}
                                    <button type="submit" name="action" value="Logout" class="btn btn-danger">Logout</button>
                            </form>
                            <br/>
                        </div>
                    {% else %}
                         <form action="{%url 'index' %}" method= "POST">
                                {% csrf_token %}
                                Username: <input type="text" name="user"><br/>
                                Password: <input type="text" name="password"><br/>
                                <button type="submit" name="action" value="Login" class="btn btn-secondary">Login</button>
                         </form>
                         {% if no_usuario %}
                            <div class="alert alert-danger" >
                                Datos erroneos. Introduzca datos válidos por favor
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="menu2">
            {% for link in menu_links %}
                <div class="menu">
                {{link | safe}}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        {% block body %}
        {% endblock %}
    </div>
    <div class="row">
        <p></p>
        {% if enlaces %}
        <div class="pie">
            <p></p>
            <p>{{enlaces | safe}}</p>
            <p></p>
        </div>
        {% endif %}
        <p></p>
    </div>
</div>
</body>
</html>